import {
    createSelector,
    createEntityAdapter
} from "@reduxjs/toolkit";
// createEntityAdapter is a function that takes an object with a selectId function and returns an object with a set of functions that can be used to manipulate the state of an entity collection
// createSelector is a function that takes an array of input selectors and a transform function and returns a memoized selector function


import { apiSlice } from "../../app/api/apiSlice"

const notesAdapter = createEntityAdapter({
    sortComparer: (a, b) => (a.completed === b.completed) ? 0 : a.completed ? 1 : -1
    // sortComparer is a function that takes two entities and returns a number 
    // if the number is less than 0, a is sorted before b
    // if the number is greater than 0, b is sorted before a
    // if the number is 0, a and b are considered equal

    // this sortComparer function sorts notes by completed status
})

const initialState = notesAdapter.getInitialState()


// apiSlice.injectEndpoints(...): This is a method provided by Redux Toolkit's createApi function. It allows you to define endpoints for your API slice.

// getNotes: builder.query(...): This is defining an endpoint for getting notes. builder.query is a method for defining a query endpoint, which is typically used for GET requests.

// query: () => '/notes': This is defining the URL for the endpoint. When this query is run, it will make a GET request to /notes.

// validateStatus: (response, result) => {...}: This is a function that checks the status of the response. It returns true if the status is 200 and there is no error, and false otherwise.

// keepUnusedDataFor: 5: This is an option that tells Redux Toolkit to keep unused data for 5 seconds before garbage collecting it.

// transformResponse: responseData => {...}: This is a function that transforms the response data before it's stored in Redux. In this case, it's mapping over the response data, changing _id to id for each note, and then using notesAdapter.setAll to store the notes in Redux.

// providesTags: (result, error, arg) => {...}: This is a function that provides tags for the query. Tags are used by Redux Toolkit to automatically refetch data when it becomes invalidated. In this case, it's providing a tag for each note ID, as well as a tag for the list of all notes.
export const notesApiSlice = apiSlice.injectEndpoints({
    endpoints: builder => ({
        getNotes: builder.query({
            query: () => '/notes',
            validateStatus: (response, result) => {
                return response.status === 200 && !result.isError
            },
            keepUnusedDataFor: 5,
            transformResponse: responseData => {
                const loadedNotes = responseData.map(note => {
                    note.id = note._id
                    return note
                });
                return notesAdapter.setAll(initialState, loadedNotes)
            },
            providesTags: (result, error, arg) => {
                if (result?.ids) {
                    return [
                        { type: 'Note', id: 'LIST' },
                        ...result.ids.map(id => ({ type: 'Note', id }))
                    ]
                } else return [{ type: 'Note', id: 'LIST' }]
            }
        }),
    }),
})

// export const { useGetNotesQuery } = notesApiSlice: This line is exporting a hook generated by Redux Toolkit's createAsyncThunk. This hook can be used in your components to fetch notes data.

// export const selectNotesResult = notesApiSlice.endpoints.getNotes.select(): This line is creating and exporting a selector that returns the result object of the getNotes query.

// const selectNotesData = createSelector(...): This line is creating a memoized selector using Redux's createSelector function. This selector takes the result of selectNotesResult and returns the data property of the result, which is the normalized state object with ids and entities.

// export const { selectAll: selectAllNotes, selectById: selectNoteById, selectIds: selectNoteIds } = notesAdapter.getSelectors(...): This line is creating and exporting several selectors using the getSelectors method of notesAdapter. These selectors can be used to select all notes, select a note by ID, and select all note IDs. The argument to getSelectors is a function that returns the notes slice of state.
export const {
    useGetNotesQuery,
} = notesApiSlice

// returns the query result object
export const selectNotesResult = notesApiSlice.endpoints.getNotes.select()

// creates memoized selector
const selectNotesData = createSelector(
    selectNotesResult,
    notesResult => notesResult.data // normalized state object with ids & entities
)

//getSelectors creates these selectors and we rename them with aliases using destructuring
export const {
    selectAll: selectAllNotes,
    selectById: selectNoteById,
    selectIds: selectNoteIds
    // Pass in a selector that returns the notes slice of state
} = notesAdapter.getSelectors(state => selectNotesData(state) ?? initialState)